#!/usr/bin/env python3
"""Generate a deterministic C translation unit for the browser assets."""

from __future__ import annotations

import argparse
from pathlib import Path


ASSETS = (
    ("/", "text/html; charset=utf-8", "index.html"),
    ("/assets/app.css", "text/css; charset=utf-8", "app.css"),
    ("/assets/app.js", "text/javascript; charset=utf-8", "app.js"),
    ("/assets/ps5-console.png", "image/png", "ps5-console.png"),
)


def bytes_literal(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16]))
    return ",\n".join(rows)


def generate(web_dir: Path) -> str:
    definitions = []
    entries = []
    for index, (url, content_type, filename) in enumerate(ASSETS):
        data = (web_dir / filename).read_bytes()
        definitions.append(
            f"static const unsigned char asset_{index}[] = {{\n{bytes_literal(data)}\n}};"
        )
        entries.append(
            '    {"%s", "%s", asset_%d, sizeof(asset_%d)}'
            % (url, content_type, index, index)
        )
    return """/* Generated by tools/embed_assets.py. Do not edit. */
#include "assets.h"

#include <string.h>

%s

static const embedded_asset_t assets[] = {
%s
};

const embedded_asset_t *assets_find(const char *path) {
    size_t index;
    if (path == NULL) {
        return NULL;
    }
    for (index = 0U; index < sizeof(assets) / sizeof(assets[0]); ++index) {
        if (strcmp(path, assets[index].path) == 0) {
            return &assets[index];
        }
    }
    return NULL;
}
""" % ("\n\n".join(definitions), ",\n".join(entries))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--web-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = generate(args.web_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
        with args.output.open("w", encoding="utf-8", newline="\n") as output:
            output.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
